"""Minimal markdown → DOCX converter for proposal drafts.

Phase 3 Week 13 (UX Sprint 6). The Sources Sought drafter outputs
markdown with this small subset:

  # H1 / ## H2 / ### H3 headings
  Plain paragraphs
  - Bulleted lists (single level)
  **bold** and *italic* inline runs

That's all the prompt is allowed to produce, so we don't need a full
markdown parser. A few hundred lines of custom logic is friendlier
than pulling in a heavy markdown lib + lossy docx mapper.
"""

from __future__ import annotations

import io
import re
from dataclasses import dataclass

from docx import Document  # type: ignore[import-untyped]
from docx.shared import Pt  # type: ignore[import-untyped]

_HEADING_RE = re.compile(r"^(#{1,3})\s+(.+?)\s*$")
_BULLET_RE = re.compile(r"^\s*[-*]\s+(.+?)\s*$")
_INLINE_RE = re.compile(r"(\*\*[^*]+\*\*|\*[^*]+\*)")


@dataclass(frozen=True)
class DocxMetadata:
    title: str
    subject: str
    author: str | None = None


def _add_styled_runs(paragraph, text: str) -> None:
    """Tokenize inline markdown (**bold**, *italic*) and add runs."""
    parts = _INLINE_RE.split(text)
    for part in parts:
        if not part:
            continue
        if part.startswith("**") and part.endswith("**") and len(part) > 4:
            run = paragraph.add_run(part[2:-2])
            run.bold = True
        elif part.startswith("*") and part.endswith("*") and len(part) > 2:
            run = paragraph.add_run(part[1:-1])
            run.italic = True
        else:
            paragraph.add_run(part)


def markdown_to_docx_bytes(
    markdown: str,
    *,
    metadata: DocxMetadata,
) -> bytes:
    """Render markdown to a DOCX file and return the binary blob."""
    doc = Document()

    # Document properties (visible in Word's File → Properties).
    core_props = doc.core_properties
    core_props.title = metadata.title[:255]
    core_props.subject = metadata.subject[:255]
    if metadata.author:
        core_props.author = metadata.author[:64]
    core_props.comments = "Generated by MacTech CaptureOS"

    # Default body font — federal-friendly, consistent with the on-screen
    # markdown editor's monospace -> proportional flip on export.
    style = doc.styles["Normal"]
    if style.font is not None:
        style.font.name = "Times New Roman"
        style.font.size = Pt(11)

    # Cover-style title at the top.
    title_para = doc.add_heading(metadata.title, level=0)
    if title_para.runs:
        title_para.runs[0].font.size = Pt(18)

    lines = markdown.splitlines()
    i = 0
    while i < len(lines):
        line = lines[i]
        stripped = line.rstrip()

        # Blank line → paragraph break.
        if not stripped:
            i += 1
            continue

        # Heading.
        m_head = _HEADING_RE.match(stripped)
        if m_head:
            level = len(m_head.group(1))
            text = m_head.group(2)
            doc.add_heading(text, level=min(level, 4))
            i += 1
            continue

        # Bulleted list — gather contiguous bullet lines.
        if _BULLET_RE.match(stripped):
            while i < len(lines):
                m_b = _BULLET_RE.match(lines[i].rstrip())
                if not m_b:
                    break
                bullet_text = m_b.group(1)
                p = doc.add_paragraph(style="List Bullet")
                _add_styled_runs(p, bullet_text)
                i += 1
            continue

        # Plain paragraph — gather contiguous non-blank, non-bullet,
        # non-heading lines.
        para_lines: list[str] = []
        while i < len(lines):
            cur = lines[i].rstrip()
            if not cur or _HEADING_RE.match(cur) or _BULLET_RE.match(cur):
                break
            para_lines.append(cur)
            i += 1
        if para_lines:
            text = " ".join(para_lines)
            p = doc.add_paragraph()
            _add_styled_runs(p, text)

    # Footer attribution.
    section = doc.sections[0]
    footer_para = section.footer.paragraphs[0]
    footer_para.text = "MacTech Solutions LLC · CaptureOS-generated draft"
    if footer_para.runs:
        footer_para.runs[0].font.size = Pt(8)

    buf = io.BytesIO()
    doc.save(buf)
    return buf.getvalue()
