import Link from "next/link";
import type { TermExplanationResponse } from "@/lib/api";

/**
 * Plain-English term explainer rail. Pages that want to support the
 * <ExplainLink>-driven `?explain=` URL pattern read the searchParam,
 * fetch /explain/{slug}, and render this rail next to their main
 * content.
 *
 * The ``closeHref`` prop is the URL to navigate to when the user
 * dismisses the rail — typically the same page minus the ?explain
 * search param. Caller is responsible for computing it.
 *
 * Originally inline in /opportunities/[id]; extracted so pursuit
 * detail, capture package, and other surfaces can opt in.
 */
export function ExplainRail({
  slug,
  explanation,
  closeHref,
}: {
  slug: string;
  explanation: TermExplanationResponse | null;
  closeHref: string;
}) {
  return (
    <aside className="lg:sticky lg:top-6 lg:self-start" aria-label="Explain">
      <div className="rounded-md border border-brand-200 bg-brand-50 p-5">
        <div className="flex items-start justify-between gap-3">
          <div className="min-w-0">
            <p className="text-[11px] font-medium uppercase tracking-wide text-brand-700">
              Explain this
            </p>
            <h3 className="mt-1 text-base font-semibold text-neutral-900">
              {explanation?.label ?? slug}
            </h3>
          </div>
          <Link
            href={closeHref}
            className="shrink-0 rounded-md p-1 text-neutral-500 hover:bg-white hover:text-neutral-800"
            aria-label="Close explanation"
            title="Close"
            scroll={false}
          >
            ✕
          </Link>
        </div>

        {explanation ? (
          <>
            <p className="mt-4 text-sm font-semibold leading-relaxed text-neutral-900">
              {explanation.summary}
            </p>
            <div className="mt-3 space-y-3 text-sm leading-relaxed text-neutral-700">
              {explanation.body
                .split(/\n{2,}/)
                .filter((p) => p.trim().length > 0)
                .map((para, i) => (
                  <p key={i}>{para}</p>
                ))}
            </div>
            <p className="mt-4 border-t border-brand-200 pt-3 text-[11px] text-neutral-500">
              {explanation.cached
                ? "Cached. "
                : "Generated by Claude Haiku. Cached for next time. "}
              Plain-English explainer.
            </p>
          </>
        ) : (
          <p className="mt-4 text-sm text-neutral-700">
            Couldn&rsquo;t generate an explanation for{" "}
            <span className="font-mono text-xs">{slug}</span>. The
            Anthropic API may be unavailable; try again in a moment.
          </p>
        )}
      </div>

      <p className="mt-3 text-[11px] text-neutral-500">
        Tip: any chip with a small{" "}
        <span className="text-brand-700">?</span> opens this rail with
        that term&rsquo;s explanation.
      </p>
    </aside>
  );
}
